export const countriesCodes = [
  {
    name: 'Afghanistan',
    code: 'AF',
    countryPassportCode: 'AFG',
    countryCode4: 'AFGH',
  },
  {
    name: 'Åland Islands',
    code: 'AX',
    countryPassportCode: 'ALA',
    countryCode4: 'ALAN',
  },
  {
    name: 'Albania',
    code: 'AL',
    countryPassportCode: 'ALB',
    countryCode4: 'ALBA',
  },
  {
    name: 'Algeria',
    code: 'DZ',
    countryPassportCode: 'DZA',
    countryCode4: 'ALGE',
  },
  {
    name: 'American Samoa',
    code: 'AS',
    countryPassportCode: 'ASM',
    countryCode4: 'ASAM',
  },
  {
    name: 'Andorra',
    code: 'AD',
    countryPassportCode: 'AND',
    countryCode4: 'ANDO',
  },
  {
    name: 'Angola',
    code: 'AO',
    countryPassportCode: 'AGO',
    countryCode4: 'ANGA',
  },
  {
    name: 'Anguilla',
    code: 'AI',
    countryPassportCode: 'AIA',
    countryCode4: 'ANGU',
  },
  {
    name: 'Antarctica',
    code: 'AQ',
    countryPassportCode: 'ATA',
    countryCode4: 'ANTA',
  },
  {
    name: 'Antigua and Barbuda',
    code: 'AG',
    countryPassportCode: 'ATG',
    countryCode4: 'ANBA',
  },
  {
    name: 'Argentina',
    code: 'AR',
    countryPassportCode: 'ARG',
    countryCode4: 'ARGE',
  },
  {
    name: 'Armenia',
    code: 'AM',
    countryPassportCode: 'ARM',
    countryCode4: 'ARME',
  },
  {
    name: 'Aruba',
    code: 'AW',
    countryPassportCode: 'ABW',
    countryCode4: 'ARUB',
  },
  {
    name: 'Australia',
    code: 'AU',
    countryPassportCode: 'AUS',
    countryCode4: 'A',
  },
  {
    name: 'Austria',
    code: 'AT',
    countryPassportCode: 'AUT',
    countryCode4: 'AUST',
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    countryPassportCode: 'AZE',
    countryCode4: 'AZER',
  },
  {
    name: 'Bahamas',
    code: 'BS',
    countryPassportCode: 'BHS',
    countryCode4: 'BHMS',
  },
  {
    name: 'Bahrain',
    code: 'BH',
    countryPassportCode: 'BHR',
    countryCode4: 'BAHR',
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    countryPassportCode: 'BGD',
    countryCode4: 'BDES',
  },
  {
    name: 'Barbados',
    code: 'BB',
    countryPassportCode: 'BRB',
    countryCode4: 'BARS',
  },
  {
    name: 'Belarus',
    code: 'BY',
    countryPassportCode: 'BLR',
    countryCode4: 'BYEL',
  },
  {
    name: 'Belgium',
    code: 'BE',
    countryPassportCode: 'BEL',
    countryCode4: 'BELM',
  },
  {
    name: 'Belize',
    code: 'BZ',
    countryPassportCode: 'BLZ',
    countryCode4: 'BELZ',
  },
  {
    name: 'Benin',
    code: 'BJ',
    countryPassportCode: 'BEN',
    countryCode4: 'BENI',
  },
  {
    name: 'Bermuda',
    code: 'BM',
    countryPassportCode: 'BMU',
    countryCode4: 'BERM',
  },
  {
    name: 'Bhutan',
    code: 'BT',
    countryPassportCode: 'BTN',
    countryCode4: 'BHUT',
  },
  {
    name: 'Bolivia',
    code: 'BO',
    countryPassportCode: 'BOL',
    countryCode4: 'BOLI',
  },
  {
    name: 'Bonaire, Saint E & S',
    code: 'BES',
    countryPassportCode: 'BES',
    countryCode4: 'BSES',
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    countryPassportCode: 'BIH',
    countryCode4: 'BOHE',
  },
  {
    name: 'Botswana',
    code: 'BW',
    countryPassportCode: 'BWA',
    countryCode4: 'BOTS',
  },
  {
    name: 'Bouvet Island',
    code: 'BI',
    countryPassportCode: 'BVI',
    countryCode4: 'BVTI',
  },
  {
    name: 'Brazil',
    code: 'BR',
    countryPassportCode: 'BRA',
    countryCode4: 'BRAZ',
  },
  {
    name: 'British Depend Territory City',
    code: 'BC',
    countryPassportCode: 'BTC',
    countryCode4: 'BDTC',
  },
  {
    name: 'British Indian Ocean Territory',
    code: 'IO',
    countryPassportCode: 'IOT',
    countryCode4: 'BIOT',
  },
  {
    name: 'British Overseas Territories Citizen',
    code: 'BO',
    countryPassportCode: 'BOC',
    countryCode4: 'BOTC',
  },
  {
    name: 'British West Indies',
    code: 'BW',
    countryPassportCode: 'BWI',
    countryCode4: 'BWIN',
  },

  {
    name: 'Brunei Darussalam',
    code: 'BN',
    countryPassportCode: 'BRN',
    countryCode4: 'BRUI',
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    countryPassportCode: 'BGR',
    countryCode4: 'BULG',
  },
  {
    name: 'Burkina Faso',
    code: 'BF',
    countryPassportCode: 'BFA',
    countryCode4: 'UVOL',
  },
  {
    name: 'Burundi',
    code: 'BI',
    countryPassportCode: 'BDI',
    countryCode4: 'BURU',
  },

  {
    name: 'Cabo Verde',
    code: 'CPV',
    countryPassportCode: 'CPV',
    countryCode4: 'CABV',
  },

  {
    name: 'Cambodia',
    code: 'KH',
    countryPassportCode: 'KHM',
    countryCode4: 'CAMB',
  },
  {
    name: 'Cameroon',
    code: 'CM',
    countryPassportCode: 'CMR',
    countryCode4: 'CREP',
  },
  {
    name: 'Canada',
    code: 'CA',
    countryPassportCode: 'CAN',
    countryCode4: 'CANA',
  },
  {
    name: 'Cape Verde',
    code: 'CV',
    countryPassportCode: 'CPV',
    countryCode4: 'CVER',
  },
  {
    name: 'Cayman Islands',
    code: 'KY',
    countryPassportCode: 'CYM',
    countryCode4: 'CAIS',
  },
  {
    name: 'Central African Republic',
    code: 'CF',
    countryPassportCode: 'CAF',
    countryCode4: 'CARE',
  },
  {
    name: 'Chad',
    code: 'TD',
    countryPassportCode: 'TCD',
    countryCode4: 'CHAD',
  },
  {
    name: 'Channel',
    code: 'CE',
    countryPassportCode: 'CHANN',
    countryCode4: 'CLIS',
  },
  {
    name: 'Chile',
    code: 'CL',
    countryPassportCode: 'CHL',
    countryCode4: 'CHIL',
  },
  {
    name: 'China',
    code: 'CN',
    countryPassportCode: 'CHN',
    countryCode4: 'PRCH',
  },
  {
    name: 'Christmas Island',
    code: 'CX',
    countryPassportCode: 'CXR',
    countryCode4: 'CSIS',
  },
  {
    name: 'Cocos (Keeling) Islands',
    code: 'CC',
    countryPassportCode: 'CCK',
    countryCode4: 'COCO',
  },
  {
    name: 'Colombia',
    code: 'CO',
    countryPassportCode: 'COL',
    countryCode4: 'COLA',
  },
  {
    name: 'Comoros',
    code: 'KM',
    countryPassportCode: 'COM',
    countryCode4: 'COMO',
  },
  {
    name: 'Congo',
    code: 'CG',
    countryPassportCode: 'COG',
    countryCode4: 'CONG',
  },
  {
    name: 'Congo, Democratic Republic',
    code: 'CD',
    countryPassportCode: 'COD',
    countryCode4: 'CODG',
  },

  {
    name: 'Cook Islands',
    code: 'CK',
    countryPassportCode: 'COK',
    countryCode4: 'COOI',
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    countryPassportCode: 'CRI',
    countryCode4: 'CRIC',
  },
  {
    name: "Cote D'IVOIRE",
    code: 'CIV',
    countryPassportCode: 'CIV',
    countryCode4: 'ICOA',
  },
  {
    name: 'Croatia',
    code: 'HR',
    countryPassportCode: 'HRV',
    countryCode4: 'CROA',
  },
  {
    name: 'Cuba',
    code: 'CU',
    countryPassportCode: 'CUB',
    countryCode4: 'CUBA',
  },
  {
    name: 'Curacao',
    code: 'CUW',
    countryPassportCode: 'CUW',
    countryCode4: 'CURA',
  },
  {
    name: 'Cyprus',
    code: 'CY',
    countryPassportCode: 'CYP',
    countryCode4: 'CYPR',
  },
  {
    name: 'Czech Republic',
    code: 'CZ',
    countryPassportCode: 'CZE',
    countryCode4: 'CZER',
  },
  {
    name: 'Czechia (Czech Rep)',
    code: 'CZE',
    countryPassportCode: 'CZE',
    countryCode4: 'CZEH',
  },
  {
    name: 'Czechoslovakia',
    code: 'CJE',
    countryPassportCode: 'DNK',
    countryCode4: 'CZEC',
  },
  {
    name: 'Denmark',
    code: 'DK',
    countryPassportCode: 'DNK',
    countryCode4: 'DENM',
  },
  {
    name: 'Djibouti',
    code: 'DJ',
    countryPassportCode: 'DJI',
    countryCode4: 'JIBU',
  },
  {
    name: 'Dominica',
    code: 'DM',
    countryPassportCode: 'DMA',
    countryCode4: 'DOMI',
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    countryPassportCode: 'DOM',
    countryCode4: 'DREP',
  },
  {
    name: 'Ecuador',
    code: 'EC',
    countryPassportCode: 'ECU',
    countryCode4: 'ECUA',
  },
  {
    name: 'Egypt',
    code: 'EG',
    countryPassportCode: 'EGY',
    countryCode4: 'EGYP',
  },
  {
    name: 'El Salvador',
    code: 'SV',
    countryPassportCode: 'SLV',
    countryCode4: 'ESAL',
  },
  {
    name: 'England',
    code: 'EN',
    countryPassportCode: 'ENG',
    countryCode4: 'ENGL',
  },
  {
    name: 'Equatorial Guinea',
    code: 'GQ',
    countryPassportCode: 'GNQ',
    countryCode4: 'EQGN',
  },
  {
    name: 'Eritrea',
    code: 'ER',
    countryPassportCode: 'ERI',
    countryCode4: 'ERIT',
  },
  {
    name: 'Estonia',
    code: 'EE',
    countryPassportCode: 'EST',
    countryCode4: 'ESTO',
  },
  {
    name: 'Eswatini',
    code: 'SZ',
    countryPassportCode: 'SWZ',
    countryCode4: 'SWZ',
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    countryPassportCode: 'ETH',
    countryCode4: 'ETHI',
  },
  {
    name: 'Falkland Island',
    code: 'FA',
    countryPassportCode: 'FAL',
    countryCode4: 'FALI',
  },
  {
    name: 'Faroe Island',
    code: 'FS',
    countryPassportCode: 'FAS',
    countryCode4: 'FAIS',
  },
  {
    name: 'Fiji',
    code: 'FJ',
    countryPassportCode: 'FJI',
    countryCode4: 'FIJI',
  },
  {
    name: 'Finland',
    code: 'FI',
    countryPassportCode: 'FIN',
    countryCode4: 'FINL',
  },
  {
    name: 'France',
    code: 'FR',
    countryPassportCode: 'FRA',
    countryCode4: 'FRAE',
  },
  {
    name: 'Franch Guiana',
    code: 'GF',
    countryPassportCode: 'GUF',
    countryCode4: 'GUYE',
  },
  {
    name: 'Franch Polynesia',
    code: 'PY',
    countryPassportCode: 'PYF',
    countryCode4: 'FPOL',
  },
  {
    name: 'Fyr Macedonia',
    code: 'FR',
    countryPassportCode: 'MKD',
    countryCode4: 'NKDA',
  },

  {
    name: 'Gabon',
    code: 'GA',
    countryPassportCode: 'GAB',
    countryCode4: 'GABO',
  },
  {
    name: 'Gambia',
    code: 'GM',
    countryPassportCode: 'GMB',
    countryCode4: 'GAMB',
  },
  {
    name: 'Gaza Strip',
    code: 'GZ',
    countryPassportCode: 'GABA',
    countryCode4: 'GAZA',
  },
  {
    name: 'Georgia',
    code: 'GE',
    countryPassportCode: 'GEO',
    countryCode4: 'GEOG',
  },
  {
    name: 'Georgia/Sandwich Island',
    code: 'GI',
    countryPassportCode: 'SGEO',
    countryCode4: 'SGIS',
  },
  {
    name: 'German Democratic Republic',
    code: 'DR',
    countryPassportCode: 'DEG',
    countryCode4: 'GDR',
  },
  {
    name: 'Germany',
    code: 'DE',
    countryPassportCode: 'D',
    countryCode4: 'GERM',
  },
  {
    name: 'Ghana',
    code: 'GH',
    countryPassportCode: 'GHA',
    countryCode4: 'GHAN',
  },
  {
    name: 'Gibraltar',
    code: 'GH',
    countryPassportCode: 'GIB',
    countryCode4: 'GIBR',
  },
  {
    name: 'Greece',
    code: 'GR',
    countryPassportCode: 'GRC',
    countryCode4: 'GREE',
  },
  {
    name: 'Greenland',
    code: 'GH',
    countryPassportCode: 'GRL',
    countryCode4: 'GRED',
  },
  {
    name: 'Grenada',
    code: 'GD',
    countryPassportCode: 'GRD',
    countryCode4: 'GREN',
  },
  {
    name: 'Guadeloupe',
    code: 'GP',
    countryPassportCode: 'GLP',
    countryCode4: 'GUAE',
  },
  {
    name: 'Guam',
    code: 'GH',
    countryPassportCode: 'GUM',
    countryCode4: 'GUAM',
  },
  {
    name: 'Guatemala',
    code: 'GT',
    countryPassportCode: 'GTM',
    countryCode4: 'GUAT',
  },
  {
    name: 'GUERNSEY',
    code: 'GU',
    countryPassportCode: 'GUE',
    countryCode4: 'GUER',
  },
  {
    name: 'Guinea',
    code: 'GN',
    countryPassportCode: 'GIN',
    countryCode4: 'GUIN',
  },
  {
    name: 'Guinea-Bissau',
    code: 'GW',
    countryPassportCode: 'GNB',
    countryCode4: 'GUBS',
  },
  {
    name: 'Guyana',
    code: 'GY',
    countryPassportCode: 'GUY',
    countryCode4: 'GUIN',
  },
  {
    name: 'Haiti',
    code: 'HT',
    countryPassportCode: 'HTI',
    countryCode4: 'HAIT',
  },
  {
    name: 'HEARD & MCDONALD ISLAND',
    code: 'HM',
    countryPassportCode: 'HMI',
    countryCode4: 'HNDI',
  },
  {
    name: 'Honduras',
    code: 'HN',
    countryPassportCode: 'HND',
    countryCode4: 'HOND',
  },
  {
    name: 'HON KONG SAR',
    code: 'HK',
    countryPassportCode: 'HKG',
    countryCode4: 'HKON',
  },

  {
    name: 'Hungary',
    code: 'HU',
    countryPassportCode: 'HUN',
    countryCode4: 'HUNG',
  },
  {
    name: 'Iceland',
    code: 'IS',
    countryPassportCode: 'ISL',
    countryCode4: 'ICEL',
  },
  {
    name: 'India',
    code: 'IN',
    countryPassportCode: 'IND',
    countryCode4: 'INDI',
  },
  {
    name: 'Indonesia',
    code: 'ID',
    countryPassportCode: 'IDN',
    countryCode4: 'IDNO',
  },
  {
    name: 'Iran',
    code: 'IR',
    countryPassportCode: 'IRN',
    countryCode4: 'IRAN',
  },
  {
    name: 'Iraq',
    code: 'IQ',
    countryPassportCode: 'IRQ',
    countryCode4: 'IRAQ',
  },

  {
    name: 'Ireland',
    code: 'IE',
    countryPassportCode: 'IRL',
    countryCode4: 'IREP',
  },
  {
    name: 'ISLE OF MAN',
    code: 'IM',
    countryPassportCode: 'MAN',
    countryCode4: 'IMAN',
  },
  {
    name: 'Israel',
    code: 'IL',
    countryPassportCode: 'ISR',
    countryCode4: 'ISRA',
  },
  {
    name: 'Italy',
    code: 'IT',
    countryPassportCode: 'ITA',
    countryCode4: 'ITAL',
  },
  {
    name: 'Jamaica',
    code: 'JM',
    countryPassportCode: 'JAM',
    countryCode4: 'JAMA',
  },
  {
    name: 'Japan',
    code: 'JP',
    countryPassportCode: 'JPN',
    countryCode4: 'JAPA',
  },

  {
    name: 'JERSEY',
    code: 'JE',
    countryPassportCode: 'JER',
    countryCode4: 'JERS',
  },
  {
    name: 'Jordan',
    code: 'JO',
    countryPassportCode: 'JOR',
    countryCode4: 'JORD',
  },
  {
    name: 'Kazakhstan',
    code: 'KZ',
    countryPassportCode: 'KAZ',
    countryCode4: 'KAZA',
  },
  {
    name: 'Kenya',
    code: 'KE',
    countryPassportCode: 'KEN',
    countryCode4: 'KENY',
  },
  {
    name: 'Kiribati',
    code: 'KI',
    countryPassportCode: 'KIR',
    countryCode4: 'GIIS',
  },
  {
    name: 'KOREA (SO STATED)',
    code: 'KSS',
    countryPassportCode: 'KTs',
    countryCode4: 'KORE',
  },
  {
    name: 'KOREA, NORTH',
    code: 'KN',
    countryPassportCode: 'PKR',
    countryCode4: 'NKOR',
  },
  {
    name: 'KOREA, SOUTH',
    code: 'KS',
    countryPassportCode: 'KOR',
    countryCode4: 'SKOR',
  },
  {
    name: 'KOSOVO',
    code: 'KK',
    countryPassportCode: 'RKS',
    countryCode4: 'KOSO',
  },
  {
    name: 'Kuwait',
    code: 'KW',
    countryPassportCode: 'KWT',
    countryCode4: 'KUWA',
  },
  {
    name: 'Kyrgyzstan',
    code: 'KG',
    countryPassportCode: 'KGZ',
    countryCode4: 'KIRG',
  },
  {
    name: 'Laos',
    code: 'LA',
    countryPassportCode: 'LAO',
    countryCode4: 'LAOS',
  },
  {
    name: 'Latvia',
    code: 'LV',
    countryPassportCode: 'LVA',
    countryCode4: 'LATV',
  },
  {
    name: 'Lebanon',
    code: 'LB',
    countryPassportCode: 'LBN',
    countryCode4: 'LEBA',
  },
  {
    name: 'Lesotho',
    code: 'LS',
    countryPassportCode: 'LSO',
    countryCode4: 'LESO',
  },
  {
    name: 'Liberia',
    code: 'LR',
    countryPassportCode: 'LBR',
    countryCode4: 'LIBE',
  },
  {
    name: 'Libya',
    code: 'LY',
    countryPassportCode: 'LBY',
    countryCode4: 'LIBA',
  },
  {
    name: 'LIBYAN ARAB JAMAHIRI',
    code: 'LAJ',
    countryPassportCode: 'LAJ',
    countryCode4: 'LIBY',
  },
  {
    name: 'Liechtenstein',
    code: 'LI',
    countryPassportCode: 'LIE',
    countryCode4: 'LIEC',
  },
  {
    name: 'Lithuania',
    code: 'LT',
    countryPassportCode: 'LTU',
    countryCode4: 'LITH',
  },

  {
    name: 'Luxembourg',
    code: 'LU',
    countryPassportCode: 'LUX',
    countryCode4: 'LUXE',
  },
  {
    name: 'MACAU SPECIAL ADMIN RGNv',
    code: 'MS',
    countryPassportCode: 'MAC',
    countryCode4: 'MACS',
  },
  {
    name: 'Madagascar',
    code: 'MG',
    countryPassportCode: 'MDG',
    countryCode4: 'MADA',
  },
  {
    name: 'Malawi',
    code: 'MW',
    countryPassportCode: 'MWI',
    countryCode4: 'MALW',
  },
  {
    name: 'Malaysia',
    code: 'MY',
    countryPassportCode: 'MYS',
    countryCode4: 'MALS',
  },
  {
    name: 'Maldives',
    code: 'MV',
    countryPassportCode: 'MDV',
    countryCode4: 'MIS',
  },
  {
    name: 'Mali',
    code: 'ML',
    countryPassportCode: 'MLI',
    countryCode4: 'M',
  },
  {
    name: 'Malta',
    code: 'MT',
    countryPassportCode: 'MLT',
    countryCode4: 'MALT',
  },
  {
    name: 'Marshall Islands',
    code: 'MH',
    countryPassportCode: 'MHL',
    countryCode4: 'MAIS',
  },
  {
    name: 'MARTINIQUE',
    code: 'MU',
    countryPassportCode: 'MTQ',
    countryCode4: 'MART',
  },
  {
    name: 'Mauritania',
    code: 'MR',
    countryPassportCode: 'MRT',
    countryCode4: 'MAUA',
  },
  {
    name: 'Mauritius',
    code: 'MI',
    countryPassportCode: 'MUS',
    countryCode4: 'MAUS',
  },
  {
    name: 'MAYOTTE',
    code: 'MXE',
    countryPassportCode: 'MXE',
    countryCode4: 'MAYO',
  },
  {
    name: 'Mexico',
    code: 'MX',
    countryPassportCode: 'MEX',
    countryCode4: 'MEXI',
  },
  {
    name: 'Micronesia',
    code: 'FM',
    countryPassportCode: 'FSM',
    countryCode4: 'MICS',
  },
  {
    name: 'Moldova',
    code: 'MD',
    countryPassportCode: 'MDA',
    countryCode4: 'MOLD',
  },
  {
    name: 'Monaco',
    code: 'MC',
    countryPassportCode: 'MCO',
    countryCode4: 'MONA',
  },
  {
    name: 'Mongolia',
    code: 'MN',
    countryPassportCode: 'MNG',
    countryCode4: 'MONG',
  },
  {
    name: 'Montenegro',
    code: 'ME',
    countryPassportCode: 'MNE',
    countryCode4: 'MNTE',
  },
  {
    name: 'MONTSERRAT',
    code: 'MSR',
    countryPassportCode: 'MSR',
    countryCode4: 'MONT',
  },
  {
    name: 'Morocco',
    code: 'MA',
    countryPassportCode: 'MAR',
    countryCode4: 'MORO',
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    countryPassportCode: 'MOZ',
    countryCode4: 'MOZA',
  },
  {
    name: 'Myanmar',
    code: 'MM',
    countryPassportCode: 'MMR',
    countryCode4: 'MYAN',
  },
  {
    name: 'Namibia',
    code: 'NA',
    countryPassportCode: 'NAM',
    countryCode4: 'NAMI',
  },
  {
    name: 'Nauru',
    code: 'NR',
    countryPassportCode: 'NRU',
    countryCode4: 'NAUR',
  },
  {
    name: 'Nepal',
    code: 'NP',
    countryPassportCode: 'NPL',
    countryCode4: 'NEPA',
  },
  {
    name: 'Netherlands',
    code: 'NL',
    countryPassportCode: 'NLD',
    countryCode4: 'NETH',
  },
  {
    name: 'Netherland ANTILLES',
    code: 'ANT',
    countryPassportCode: 'ANT',
    countryCode4: 'NANT',
  },
  {
    name: 'NEW CALEDONIA',
    code: 'NCL',
    countryPassportCode: 'NCL',
    countryCode4: 'NCAL',
  },
  {
    name: 'NEW GUINEA',
    code: 'NLG',
    countryPassportCode: 'NLG',
    countryCode4: 'NEGG',
  },
  {
    name: 'NEW HEBRADES',
    code: 'NLH',
    countryPassportCode: 'NLH',
    countryCode4: 'NHEB',
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    countryPassportCode: 'NZL',
    countryCode4: 'NZEA',
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    countryPassportCode: 'NIC',
    countryCode4: 'NICA',
  },
  {
    name: 'Niger',
    code: 'NE',
    countryPassportCode: 'NER',
    countryCode4: 'NIGR',
  },
  {
    name: 'Nigeria',
    code: 'NG',
    countryPassportCode: 'NGA',
    countryCode4: 'NIRA',
  },
  {
    name: 'NIUE',
    code: 'NIU',
    countryPassportCode: 'NIU',
    countryCode4: 'NIUE',
  },
  {
    name: 'NORFOLK ISLAND',
    code: 'NOIS',
    countryPassportCode: 'NOIS',
    countryCode4: 'NOIS',
  },
  {
    name: 'NORTHERN IRELAND',
    code: 'NOIR',
    countryPassportCode: 'NOIR',
    countryCode4: 'NOIR',
  },
  {
    name: 'NORTHERN MARIANA ISLAND',
    code: 'NMAL',
    countryPassportCode: 'NMAL',
    countryCode4: 'NMAL',
  },
  {
    name: 'North Korea',
    code: 'KP',
    countryPassportCode: 'PRK',
    countryCode4: 'PRK',
  },
  {
    name: 'North Macedonia',
    code: 'MK',
    countryPassportCode: 'MKD',
    countryCode4: 'MKD',
  },
  {
    name: 'Norway',
    code: 'NO',
    countryPassportCode: 'NOR',
    countryCode4: 'NORW',
  },
  {
    name: 'Oman',
    code: 'OM',
    countryPassportCode: 'OMN',
    countryCode4: 'OMAN',
  },
  {
    name: 'Pakistan',
    code: 'PK',
    countryPassportCode: 'PAK',
    countryCode4: 'PKSN',
  },
  {
    name: 'Palau',
    code: 'PW',
    countryPassportCode: 'PLW',
    countryCode4: 'PALA',
  },
  {
    name: 'PALESTINIEN AUTHORTY',
    code: 'PSE',
    countryPassportCode: 'PSE',
    countryCode4: 'PALE',
  },
  {
    name: 'Panama',
    code: 'PA',
    countryPassportCode: 'PAN',
    countryCode4: 'PANA',
  },
  {
    name: 'Papua New Guinea',
    code: 'PG',
    countryPassportCode: 'PNG',
    countryCode4: 'NGUI',
  },
  {
    name: 'Paraguay',
    code: 'PY',
    countryPassportCode: 'PRY',
    countryCode4: 'PARA',
  },
  {
    name: 'Peru',
    code: 'PE',
    countryPassportCode: 'PER',
    countryCode4: 'PERU',
  },
  {
    name: 'Philippines',
    code: 'PH',
    countryPassportCode: 'PHL',
    countryCode4: 'PHIL',
  },
  {
    name: 'PITCAIRN',
    code: 'PISS',
    countryPassportCode: 'PISS',
    countryCode4: 'PISS',
  },
  {
    name: 'PLEASANT ISALND',
    code: 'PLIS',
    countryPassportCode: 'PLIS',
    countryCode4: 'PLIS',
  },
  {
    name: 'Poland',
    code: 'PL',
    countryPassportCode: 'POL',
    countryCode4: 'POLA',
  },
  {
    name: 'Portugal',
    code: 'PT',
    countryPassportCode: 'PRT',
    countryCode4: 'PORL',
  },
  {
    name: 'PUERTO RICA',
    code: 'PRI',
    countryPassportCode: 'PRI',
    countryCode4: 'PRIC',
  },
  {
    name: 'Qatar',
    code: 'QA',
    countryPassportCode: 'QAT',
    countryCode4: 'QATA',
  },
  {
    name: 'REUNION',
    code: 'REU',
    countryPassportCode: 'REU',
    countryCode4: 'REIS',
  },
  {
    name: 'Romania',
    code: 'RO',
    countryPassportCode: 'ROU',
    countryCode4: 'ROUN',
  },
  {
    name: 'Romania PER 1/2/2002',
    code: 'ROM',
    countryPassportCode: 'ROM',
    countryCode4: 'ROMN',
  },
  {
    name: 'Russian Federation',
    code: 'RU',
    countryPassportCode: 'RUS',
    countryCode4: 'RFED',
  },
  {
    name: 'Rwanda',
    code: 'RW',
    countryPassportCode: 'RWA',
    countryCode4: 'RWAN',
  },
  {
    name: 'SAINT BARTHELEMY',
    code: 'STBA',
    countryPassportCode: 'STBA',
    countryCode4: 'STBA',
  },
  {
    name: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
    code: 'SHN',
    countryPassportCode: 'SHN',
    countryCode4: 'SHTC',
  },
  {
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    countryPassportCode: 'KNA',
    countryCode4: 'SCKN',
  },
  {
    name: 'Saint Lucia',
    code: 'LC',
    countryPassportCode: 'LCA',
    countryCode4: 'STLU',
  },
  {
    name: 'SAINT MARTIN',
    code: 'STMA',
    countryPassportCode: 'STMA',
    countryCode4: 'STMA',
  },

  {
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    countryPassportCode: 'VCT',
    countryCode4: 'VCT',
  },

  {
    name: 'Samoa',
    code: 'WS',
    countryPassportCode: 'WSM',
    countryCode4: 'SAMO',
  },
  {
    name: 'San Marino',
    code: 'SM',
    countryPassportCode: 'SMR',
    countryCode4: 'SMAR',
  },
  {
    name: 'SAO TOME & PRINCIPE',
    code: 'STP',
    countryPassportCode: 'STP',
    countryCode4: 'STPR',
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    countryPassportCode: 'SAU',
    countryCode4: 'SAAR',
  },

  {
    name: 'SCOTLAND',
    code: 'SCOT',
    countryPassportCode: 'SCOT',
    countryCode4: 'SCOT',
  },
  {
    name: 'Senegal',
    code: 'SN',
    countryPassportCode: 'SEN',
    countryCode4: 'SENE',
  },
  {
    name: 'Serbia',
    code: 'RS',
    countryPassportCode: 'SRB',
    countryCode4: 'SERB',
  },
  {
    name: 'SERBIA AND MONTENEGRO',
    code: 'SCG',
    countryPassportCode: 'SCG',
    countryCode4: 'SEMO',
  },
  {
    name: 'Seychelles',
    code: 'SC',
    countryPassportCode: 'SYC',
    countryCode4: 'SEYC',
  },
  {
    name: 'Sierra Leone',
    code: 'SL',
    countryPassportCode: 'SLE',
    countryCode4: 'SLEO',
  },
  {
    name: 'Singapore',
    code: 'SG',
    countryPassportCode: 'SGP',
    countryCode4: 'SING',
  },
  {
    name: 'SINT MAARTEN (DUTCH)',
    code: 'SXM',
    countryPassportCode: 'SXM',
    countryCode4: 'SXMN',
  },
  {
    name: 'SLOVAK REPUBLIC',
    code: 'SVK',
    countryPassportCode: 'SVK',
    countryCode4: 'SVKA',
  },
  {
    name: 'SLOVENTA',
    code: 'SLOV',
    countryPassportCode: 'SLOV',
    countryCode4: 'SLOV',
  },
  {
    name: 'Slovakia',
    code: 'SK',
    countryPassportCode: 'SVK',
    countryCode4: 'SVK',
  },
  {
    name: 'Slovenia',
    code: 'SI',
    countryPassportCode: 'SVN',
    countryCode4: 'SVN',
  },
  {
    name: 'Solomon Islands',
    code: 'SB',
    countryPassportCode: 'SLB',
    countryCode4: 'SOLI',
  },
  {
    name: 'Somalia',
    code: 'SO',
    countryPassportCode: 'SOM',
    countryCode4: 'SOMA',
  },
  {
    name: 'South Africa',
    code: 'ZA',
    countryPassportCode: 'ZAF',
    countryCode4: 'SAFR',
  },
  {
    name: 'SOUTH SUDAN ',
    code: 'SD',
    countryPassportCode: 'SDN',
    countryCode4: 'SSDN',
  },

  {
    name: 'South Georgia and the South Sandwich Islands',
    code: 'GS',
    countryPassportCode: 'SGS',
    countryCode4: 'SGS',
  },

  {
    name: 'Spain',
    code: 'ES',
    countryPassportCode: 'ESP',
    countryCode4: 'SPAI',
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    countryPassportCode: 'LKA',
    countryCode4: 'SRIL',
  },
  {
    name: 'ST HELENA',
    code: 'SHEL',
    countryPassportCode: 'SHEL',
    countryCode4: 'SHEL',
  },
  {
    name: 'ST PIERRE & MIQUELON',
    code: 'STPM',
    countryPassportCode: 'STPM',
    countryCode4: 'STPM',
  },
  {
    name: 'ST VINCENT/GRENADINE',
    code: 'VCT',
    countryPassportCode: 'VCT',
    countryCode4: 'STVG',
  },

  {
    name: 'Sudan',
    code: 'SD',
    countryPassportCode: 'SDN',
    countryCode4: 'SUDA',
  },
  {
    name: 'Suriname',
    code: 'SR',
    countryPassportCode: 'SUR',
    countryCode4: 'SURI',
  },
  {
    name: 'Svalbard and Jan Mayen',
    code: 'SJ',
    countryPassportCode: 'SJM',
    countryCode4: 'SAJM',
  },
  {
    name: 'Swaziland',
    code: 'SZ',
    countryPassportCode: 'SWZ',
    countryCode4: 'SWAZ',
  },
  {
    name: 'Sweden',
    code: 'SE',
    countryPassportCode: 'SWE',
    countryCode4: 'SWED',
  },
  {
    name: 'Switzerland',
    code: 'CH',
    countryPassportCode: 'CHE',
    countryCode4: 'SWIT',
  },
  {
    name: 'Syrian Arab Republic',
    code: 'SY',
    countryPassportCode: 'SYR',
    countryCode4: 'SYRI',
  },
  {
    name: 'TAHITI',
    code: 'TAHI',
    countryPassportCode: 'TAHI',
    countryCode4: 'TAHI',
  },
  {
    name: 'Taiwan, Province of China',
    code: 'TW',
    countryPassportCode: 'TWN',
    countryCode4: 'TAIW',
  },
  {
    name: 'Tajikistan',
    code: 'TJ',
    countryPassportCode: 'TJK',
    countryCode4: 'TADZ',
  },
  {
    name: 'Tanzania, United Republic of',
    code: 'TZ',
    countryPassportCode: 'TZA',
    countryCode4: 'TANZ',
  },
  {
    name: 'Thailand',
    code: 'TH',
    countryPassportCode: 'THA',
    countryCode4: 'THAI',
  },
  {
    name: 'TIBET (SO STATED)',
    code: 'TIBE',
    countryPassportCode: 'TIBE',
    countryCode4: 'TIBE',
  },
  {
    name: 'TIMOR, EAST',
    code: 'TM',
    countryPassportCode: 'TMP',
    countryCode4: 'ETIM',
  },
  {
    name: 'Timor-Leste',
    code: 'TL',
    countryPassportCode: 'TLS',
    countryCode4: 'TILE',
  },
  {
    name: 'Togo',
    code: 'TG',
    countryPassportCode: 'TGO',
    countryCode4: 'TOGO',
  },
  {
    name: 'Tokelau',
    code: 'TK',
    countryPassportCode: 'TKL',
    countryCode4: 'TOKE',
  },
  {
    name: 'Tonga',
    code: 'TO',
    countryPassportCode: 'TON',
    countryCode4: 'TONG',
  },
  {
    name: 'Trinidad and Tobago',
    code: 'TT',
    countryPassportCode: 'TTO',
    countryCode4: 'TRIN',
  },
  {
    name: 'Tunisia',
    code: 'TN',
    countryPassportCode: 'TUN',
    countryCode4: 'TUNI',
  },
  {
    name: 'Turkey',
    code: 'TR',
    countryPassportCode: 'TUR',
    countryCode4: 'TURY',
  },
  {
    name: 'Turkmenistan',
    code: 'TM',
    countryPassportCode: 'TKM',
    countryCode4: 'TURM',
  },
  {
    name: 'Turks and Caicos Islands',
    code: 'TC',
    countryPassportCode: 'TCA',
    countryCode4: 'TCIS',
  },
  {
    name: 'Tuvalu',
    code: 'TV',
    countryPassportCode: 'TUV',
    countryCode4: 'TUVU',
  },
  {
    name: 'USSR',
    code: 'UG',
    countryPassportCode: 'UGA',
    countryCode4: 'USSR',
  },
  {
    name: 'Uganda',
    code: 'UG',
    countryPassportCode: 'UGA',
    countryCode4: 'UGAN',
  },
  {
    name: 'Ukraine',
    code: 'UA',
    countryPassportCode: 'UKR',
    countryCode4: 'UKRA',
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    countryPassportCode: 'ARE',
    countryCode4: 'UAEM',
  },
  {
    name: 'United Kingdom -British Citizen',
    code: 'GB',
    countryPassportCode: 'GBR',
    countryCode4: 'UK',
  },
  {
    name: 'UNITED KINGDOM -BRITISH NATIONAL (OVERSEAS)',
    code: 'GB',
    countryPassportCode: 'GBN',
    countryCode4: 'UK',
  },
  {
    name: 'UNITED KINGDOM -BRITISH OVERSEAS CITIZEN',
    code: 'GB',
    countryPassportCode: 'GBO',
    countryCode4: 'UK',
  },
  {
    name: 'UNITED KINGDOM -BRITISH OVERSEAS TERRITORIES CITIZEN',
    code: 'GB',
    countryPassportCode: 'GBD',
    countryCode4: 'UK',
  },
  {
    name: 'UNITED KINGDOM -BRITISH PROTECTED PERSON',
    code: 'GB',
    countryPassportCode: 'GBP',
    countryCode4: 'UK',
  },
  {
    name: 'UNITED KINGDOM -BRITISH SUBJECT',
    code: 'GB',
    countryPassportCode: 'GBS',
    countryCode4: 'UK',
  },
  {
    name: 'United States',
    code: 'US',
    countryPassportCode: 'USA',
    countryCode4: 'USA',
  },
  {
    name: 'United States Minor Outlying Islands',
    code: 'UM',
    countryPassportCode: 'UMI',
    countryCode4: 'USOI',
  },
  {
    name: 'Uruguay',
    code: 'UY',
    countryPassportCode: 'URY',
    countryCode4: 'URUG',
  },
  {
    name: 'Uzbekistan',
    code: 'UZ',
    countryPassportCode: 'UZB',
    countryCode4: 'UZBE',
  },
  {
    name: 'Vanuatu',
    code: 'VU',
    countryPassportCode: 'VUT',
    countryCode4: 'VANU',
  },
  {
    name: 'VATICAN CITY STATE',
    code: 'VU',
    countryPassportCode: 'VAT',
    countryCode4: 'VCIT',
  },
  {
    name: 'Venezuela',
    code: 'VE',
    countryPassportCode: 'VEN',
    countryCode4: 'VENE',
  },
  {
    name: 'Vietnam',
    code: 'VN',
    countryPassportCode: 'VNM',
    countryCode4: 'VIET',
  },
  {
    name: 'Virgin Islands, British',
    code: 'VG',
    countryPassportCode: 'VGB',
    countryCode4: 'VIIS',
  },
  {
    name: 'Virgin Islands, U.S.',
    code: 'VI',
    countryPassportCode: 'VIR',
    countryCode4: 'VIUK',
  },
  {
    name: 'WALES',
    code: 'VU',
    countryPassportCode: 'VUT',
    countryCode4: 'WALE',
  },
  {
    name: 'Wallis and Futuna',
    code: 'WF',
    countryPassportCode: 'WLF',
    countryCode4: 'WAFU',
  },
  {
    name: 'WEST BANK',
    code: 'VU',
    countryPassportCode: 'VUT',
    countryCode4: 'WBAN',
  },
  {
    name: 'Western Sahara',
    code: 'EH',
    countryPassportCode: 'ESH',
    countryCode4: 'ESH',
  },
  {
    name: 'Yemen',
    code: 'YE',
    countryPassportCode: 'YEM',
    countryCode4: 'YEME',
  },
  {
    name: 'YUGOSLAVIA',
    code: 'YUG',
    countryPassportCode: 'YUG',
    countryCode4: 'FRY',
  },
  {
    name: 'ZAIRE',
    code: 'VU',
    countryPassportCode: 'ZAR',
    countryCode4: 'ZAIR',
  },
  {
    name: 'Zambia',
    code: 'ZM',
    countryPassportCode: 'ZMB',
    countryCode4: 'ZAMB',
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    countryPassportCode: 'ZWE',
    countryCode4: 'ZIMB',
  },
];